---
- name: Ler o arquivo /etc/hosts
  ansible.builtin.command:
    cmd: cat /etc/hosts
  register: content
  changed_when: false
  tags: hosts

- name: Limpa o arquivo /etc/hosts
  ansible.builtin.shell: echo '' > /etc/hosts
  when: "'10.2.0.11 ansible-server.4labs ansible-server' not in content.stdout"
  changed_when: false
  tags: hosts

- name: Configuracao do arquivo /etc/hosts
  when: "'10.2.0.11 ansible-server.4labs ansible-server' not in content.stdout"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.alias }}"
  with_items:
    - {ip: '127.0.0.1', fqdn: 'localhost.localdomain', alias: 'localhost'}
    - {ip: '10.2.0.11', fqdn: 'ansible-server.4labs', alias: 'ansible-server'}
    - {ip: '10.1.0.12', fqdn: 'balancer-server.4labs', alias: 'balancer-server'}
    - {ip: '10.1.0.13', fqdn: 'web-server1.4labs', alias: 'web-server1'}
    - {ip: '10.1.0.14', fqdn: 'web-server2.4labs', alias: 'web-server2'}
    - {ip: '10.1.0.15', fqdn: 'db-server.4labs', alias: 'db-server'}
  tags: hosts
